### ISSUE TITLE
Envio de forma personalizada de forma de pagamento

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#138]
**Descreva o bug**
Permitir o cliente cadastrar a forma de pagamento personalizada, fora da tabela padrão.

**Comment by leomp12** [comment]
Pra que isso? Já envia forma de pagamento diferente quando o payment method não bate algum default deles https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/parsers/order-to-tiny/index.js#L119-L121

**Comment by matheusgnreis** [comment]
Vou fechar, porque sinceramente pix é depósito mesmo, ficar encrespando com nomeclatura, é osso. O tiny associa ambos como banco.

**Comment by matheusgnreis** [comment]
Mesmo tiny falando que pode enviar como pix, que no final associa como banco
