### ISSUE TITLE
Fila de importação muito grande tendo alteração tardia

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#39]
A fila de importação da loja 1166 está muito grande, as vezes a alteração é consumada horas depois e pelo que vi, na fila primeiro é feito a busca pelos skus e depois pelas orders, porém tem uma fila enorme de sku sendo processada e por isso os dois pedidos que lá estão, já tem 1 dia que está lá travado e não tem alteração na loja virtual.

Sugiro fazer o mesmo que foi feito no bling que é receber a informação e repassar para produto ou pedido, de forma a diminuir essa fila e a alteração ser mais rápida

**Comment by matheusgnreis** [comment]
@leomp12 chegou a ver isso? Diz o paulo trucco que direto não está ocorrendo atualizações dos pedidos porque a fila está enorme de estoque

**Comment by leomp12** [comment]
Eu vou fazer uai, só não deu tempo ainda.
Não vou mexer nisso agora, se a fila está travada limpa os SKUs, deixa só
os mais recentes.

Em ter., 13 de abr. de 2021 12:57, Matheus Reis ***@***.***>
escreveu:

**Comment by matheusgnreis** [comment]
Ah sim, pensei que não tinha visto, dessa reclamação ai, atualizou só hoje de manhã, fila dele é enorme também. Vou conversar com ele, está abrindo diversos tickets de insatisfação, vou tentar explicar pra ele as coisas

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-tiny-erp/commit/aba207564a20156157be52fcf389815d9403dafe
