### ISSUE TITLE
Webhook Tiny

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#4]
Tiny nos liberou a opção de cadastro do webhook para posterior homologação. No caso, o caminho para inserção das urls é:

Configurações > E-commerce > Integrações. Clicar na integração para testes.
O ID do integrador é: 8393, se precisar.
Em notificações foi liberado todos os campos disponíveis, basta inserir e salvar que teoricamente vai estar ativo

**Comment by leomp12** [comment]
Webhooks para pedidos adicionando importação `a fila em `Order_numbers` e para produtos em `Skus`

**Comment by matheusgnreis** [comment]
Para funcionar o webhook, é necessário enviar um parâmetro pra identificar o e-commerce. Cada lojista tem um ID único, segundo o tiny, no caso da nossa é 8393.

Quando o pedido é enviado com esse parâmetro, o webhook passa a funcionar para esses pedidos.

**Comment by leomp12** [comment]
Uai mas não falaram que raio de parâmetro é esse? Haha
Sabe onde o lojista pega isso no painel do Tiny então?

Em qua, 9 de dez de 2020 19:32, Matheus Reis <notifications@github.com>
escreveu:

**Comment by leomp12** [comment]
Tem esse campo aqui no admin settings já:

![Screenshot_2020-12-10 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/101777898-df11e580-3ad1-11eb-9f61-3c2d1911d09a.png)

Vou salvar esse número e testar um pedido novo, tem que saber onde o lojista pega isso da conta dele depois...

**Comment by matheusgnreis** [comment]
Ele me passou, lá no suporte do Tiny, depois colo aqui

**Comment by leomp12** [comment]
Negócio é colocar isso no tutorial e/ou na descrição do input no admin settings.

**Comment by matheusgnreis** [comment]
O mesmo corresponde ao ID do e-commerce configurado no Tiny. Se acessar em Menu >
Configurações > E-commerce > Integrações, editar a integração que tem é o ID presente na URL da mesma, no caso da sua é 8393.

**Comment by leomp12** [comment]
Então todo lojista tem que pegar isso no URL? haha

**Comment by matheusgnreis** [comment]
Tem um botão que mostra apikey e esse número, talvez seja mais fácil explicar assim, do que essa na URL que me passaram

**Comment by leomp12** [comment]
![Screenshot_2020-12-10 Tiny - Configuração de Integração](https://user-images.githubusercontent.com/10326572/101838716-e52eb300-3b1f-11eb-8889-f5a92bd18c0f.png)

**Comment by leomp12** [comment]
Mesmo URL para as 4 notificações aí, mesmo esquema do Bling nos parâmetros...
Envio de nota fiscal e código de rastreio não são tratados, mas quando há alteração de status do pedido eles são checados também.

**Comment by matheusgnreis** [comment]
Beleza, vou testar e já informar ao tiny sobre isso, para homologarem
