### ISSUE TITLE
Erro de configuração para exportar pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#48]
Mesmo estando desativado a opção de enviar pedido, ele está sendo enviado, exemplo pedido 60a3c8a4aa82b4705e40f38a loja 1032, está desativado o envio do pedido e mesmo assim é enviado.

**Comment by leomp12** [comment]
Uai, tem certeza disso? O app está atualizado nessa loja? Você testou um pedido novo com a opção desabilitada?

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-tiny-erp/blob/master/functions/routes/ecom/webhook.js#L182
https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/export-order.js#L32-L34

**Comment by matheusgnreis** [comment]
Sim, eu testei com ele false, desmarcado (Versão 1.5.4). Até vi o código, fiz o teste e rolou dessa forma. O blow hair, tentou desativar pra enviar manualmente somente os pedidos aprovados, fiz o teste com ele desativado e enviou mesmo assim.
