### ISSUE TITLE
Forçar forma_envio X para loggi em determinada loja

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#5]
Como o cliente utiliza Loggi para calcular o frete dele, mas para entregar usa um serviço próprio de entrega, ele acaba não precisando de ser enviado pela Loggi e sim por uma forma de envio customizada que criou no Tiny. No momento, ele insere o forma_envio como T. Por causa disso, o Tiny associa a Total Express por ser a única forma de envio com T acredito eu, só isso explicaria essa bruxaria de enviar forma_frete = Motoboy e forma_envio = T, virar no tiny forma_frete = Total express

Como outros lojista também utilizam Loggi como transportadora, precisaria achar um meio termo.
Segue o objeto do pedido:

```
  "shipping_lines": [
    {
      "_id": "e16034285769401111111111",
      "app": {
        "_id": "5f6e0dba7430f92180f52d24",
        "label": "MOTOBOY",
        "carrier": "Loggi",
        "service_name": "MOTOBOY",
        "service_code": "FRLOG_02"
      },
      "from": {
        "zip": "05319000",
        "street": "Av Queiroz Filho",
        "number": 1700,
        "complement": "Conjunto 1005D",
        "near_to": "Condominio Villa Lobos Office Park",
        "borough": "Vila Hamburguesa",
        "city": "São Paulo",
        "province": "SP",
        "province_code": "SP",
        "country": "Brasil"
      },
      "to": {
        "zip": "05319000",
        "province_code": "SP",
        "name": "Matheus Guedes",
        "city": "São Paulo",
        "borough": "Vila Hamburguesa",
        "street": "Avenida Queiroz Filho",
        "number": 21
      },
      "delivery_time": {
        "days": 1,
        "working_days": true
      },
      "price": 11.62,
      "total_price": 11.62,
      "custom_fields": [
        {
          "field": "by_frenet",
          "value": "true"
        }
      ],
      "own_hand": false,
      "receipt": false
    }
  ],
  "shipping_method_label": "MOTOBOY"
```

**Comment by leomp12** [comment]
Isso é gambiarra pura, vou mockar pro Store ID, TRUCCO (`1166`) mesmo né?

**Comment by matheusgnreis** [comment]
Ou talvez colocar que se o shipping_method_label for Motoboy, será enviado como customizado, é uma forma de mocar também, só que menos, porque normalmente, se for motoboy, é uma forma de envio customizada já.

**Comment by leomp12** [comment]
Você tá falando do `label` né? Mas todo mundo que usar Loggi (talvez exista outros também) deve colocar Motoboy...

**Comment by leomp12** [comment]
Se fosse motoboy com o app de frete personalizado já iria ficar o `X` porque não teria transportadora definida.
