### ISSUE TITLE
Erro ao importar produto do tiny para plataforma

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#6]
O tiny está importando o produto com a variação embutida e cria outro produto representando a variação.

![tinyerr](https://user-images.githubusercontent.com/35343551/97088797-b610c080-1609-11eb-8d7f-dbe066d6b8ae.png)

O sku dessa variação consta dentro do produto criado

**Comment by matheusgnreis** [comment]
Além de criar as variações novas, o estoque que vem com a variação embutida não existe na variação, ou seja, dentro do produto fica com 0 junto com suas variações sem entrada de quantity como por exemplo o produto:
5f94721ab2161709fa4355d4
```
  "variations": [
    {
      "_id": "369801603564020750000000",
      "name": "Saia midi Cartagena Offwhite / P / OFFWHITE",
      "sku": "0056564714754",
      "specifications": {
        "tamanhos": [
          {
            "text": "P",
            "value": "p"
          }
        ],
        "cor": [
          {
            "text": "OFFWHITE",
            "value": "offwhite"
          }
        ]
      },
      "price": 449.9
    },
    {
      "_id": "634354160356402105200000",
      "name": "Saia midi Cartagena Offwhite / M / OFFWHITE",
      "sku": "0056564714761",
      "specifications": {
        "tamanhos": [
          {
            "text": "M",
            "value": "m"
          }
        ],
        "cor": [
          {
            "text": "OFFWHITE",
            "value": "offwhite"
          }
        ]
      },
      "price": 449.9
    }
  ]
```

**Comment by leomp12** [comment]
Qual SKU você colocou na fila nesse exemplo aí? Deveria ser só o SKU do produto, foi isso mesmo?
E os estoques das variações são atualizados depois porque o Tiny não retorna na consulta do produto, você esperou um tempo?

**Comment by matheusgnreis** [comment]
Foi o sku do produto

**Comment by leomp12** [comment]
> delay da Search API...

**Comment by matheusgnreis** [comment]
Ainda está rolando, tanto no caso de subscrever, se tiver true, como mostra a foto
![tinyerr-2](https://user-images.githubusercontent.com/35343551/97119266-d2862900-16ed-11eb-8ee8-548f557217ef.png)
Quanto no caso de buscar novo produto, cria o produto com as variações, mas sem quantidade associada, conforme https://github.com/ecomplus/app-tiny-erp/issues/8
S

**Comment by matheusgnreis** [comment]
@leomp12
