### ISSUE TITLE
Erro na importação de produto

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#68]
![image](https://user-images.githubusercontent.com/35343551/133346762-2489cba6-5180-4991-842b-31d70eb5d720.png)

**Comment by leomp12** [comment]
No print aí você pegou só o config da request, não aparece a resposta de erro então não dá pra concluir muita coisa.

Mas eu imagino o que seja, essa loja tem algum produto? Se não cria um produto qualquer manualmente, depois tenta importar novamente por favor.

**Comment by leomp12** [comment]
Pelo que vi aqui é exatamente isso, não é um bug do app no caso, o index no cluster de busca que não foi criado pra essa loja, só criar um produto qualquer e depois pode deletá-lo e a importação deve acontecer normalmente.

Depois vou fixar na API.
