### ISSUE TITLE
Erro ao importar produto não está vindo dimensões

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#7]
Importando o produto manualmente do Tiny está trazendo apenas o peso, as dimensões estão sendo desconsideradas

![tinyerr-1](https://user-images.githubusercontent.com/35343551/97091636-a5654800-1613-11eb-8976-3037a986bd4a.png)
![tinyerr-2](https://user-images.githubusercontent.com/35343551/97091641-a9916580-1613-11eb-8692-7ae783d91eab.png)

**Comment by leomp12** [comment]
É porque a [documentação](https://www.tiny.com.br/ajuda/api/api2-produtos-obter) deles diz `retorno.produto.altura_embalagem` por exemplo, mas o retorno é `alturaEmbalagem`, mesmo vale pros outros lados :neutral_face: 
Só adivinhar né...
