### ISSUE TITLE
Sincronização errada de status

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#78]
**Descreva o bug**
O pedido 61684a7e28ace502aea56aa4 atualizou para **em separação**, **pronto para envio** e depois **enviado**, conforme a imagem:
![image](https://user-images.githubusercontent.com/35343551/137382042-c0d6e688-2791-4911-b3aa-29ba2d7bb45a.png)

Porém, nós atualizamos eles pra ponto pra envio apenas, conforme a imagem deles:

![WhatsApp Image 2021-10-14 at 15 07 29](https://user-images.githubusercontent.com/35343551/137382451-a0f0ca5c-e247-46c8-87c6-afbcb8961d26.jpeg)

E aqui informando que enviamos naquela hora só o pronto pra envio de fato:

![image](https://user-images.githubusercontent.com/35343551/137381656-4c070789-7b68-43d0-9f59-5b490b206388.png)

E ai tiveram que fazer uma ação manual e colocar como enviado novamente.
Me passaram 4 pedidos que ocorreu isso, ontem eu vi um que atualizou pra pronto pra envio, pra enviado e pronto pra envio de novo. Mas como tinha sido um caso só, eu deixei pra lá, ocorreram outros hoje.

**Comment by leomp12** [comment]
Foi atualizado na plataforma então, certo? E o shipped não foi pro Tiny...
Vou ver o shipped especificamente

**Comment by matheusgnreis** [comment]
Isso, o shipped não foi.
