### ISSUE TITLE
Quantidade não sendo inserida na variação ao importar

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-tiny-erp#8]
O produto continua vindo sem o quantity na variação
```
"variations": [
    {
      "_id": "487718160366002033300000",
      "name": "Saia Cuba Libre Coco Queimado / P / COCO QUEIMADO",
      "sku": "0056564690430",
      "specifications": {
        "tamanhos": [
          {
            "text": "P",
            "value": "p"
          }
        ],
        "cor": [
          {
            "text": "COCO QUEIMADO",
            "value": "coco queimado"
          }
        ]
      },
      "price": 449.9
    },
    {
      "_id": "889962160366002033300000",
      "name": "Saia Cuba Libre Coco Queimado / M / COCO QUEIMADO",
      "sku": "0056564690447",
      "specifications": {
        "tamanhos": [
          {
            "text": "M",
            "value": "m"
          }
        ],
        "cor": [
          {
            "text": "COCO QUEIMADO",
            "value": "coco queimado"
          }
        ]
      },
      "price": 449.9
    }
  ]
```

**Comment by matheusgnreis** [comment]
Nesse produto, coloquei depois para não dar erro no checkout

**Comment by leomp12** [comment]
@matheusgnreis a opção de sobrescrever o cadastro não muda isso, só muda se atualiza só o estoque ou outras informações também se o produto for encontrado antes, o problema aí é que o produto/variação não está sendo encontrado pelo SKU.
Você adicionou o SKU pra importar dentro do painel mesmo ou via API? Se foi via API qual foi o body exatamente?

**Comment by leomp12** [comment]
Vai continuar criando a variação sem quantity, o problema é não bater o SKU depois pra atualizar...

**Comment by matheusgnreis** [comment]
Foi no painel mesmo, coloquei o sku do produto pai

**Comment by leomp12** [comment]
Era bom se tivesse um exemplo disso na 1011 onde eu consigo testar e entrar no painel do Tiny lá.

**Comment by matheusgnreis** [comment]
O trucco me passou o acesso do tiny caso precisasse para algo, vou te passar no slack
